---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: devops
  annotations:
    notifications.argoproj.io/subscribe.slack: cicd
    argocd.argoproj.io/manifest-generate-paths: /deploy
spec:
  project: default
  source:
    repoURL: https://github.com/theautomation/home-assistant-config.git
    targetRevision: main
    path: deploy/k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: home-automation
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
